apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  name: prometheus-k8s
  namespace: openshift-sre-ethtool-exporter
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
