apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: ethtool-exporter scc used by supplemental node-exporter to provide ethtool metrics
  name: ethtool-exporter
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - runtime/default
supplementalGroups:
  type: RunAsAny
users:
  ["system:serviceaccount:openshift-sre-ethtool-exporter:ethtool-exporter-sa"]
volumes:
  - "*"
