apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: ethtool-exporter-ca-bundle
  namespace: openshift-sre-ethtool-exporter
