deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
    - key: ext-hypershift.openshift.io/cluster-type
      operator: In
      values: ["management-cluster"]
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    - key: api.openshift.com/environment
      operator: NotIn
      values:
      - "production"
