  apiVersion: operator.openshift.io/v1
  applyMode: AlwaysApply
  kind: Console
  name: cluster
  patch: '[{"op": "replace", "path": "/spec/customization/customProductName", "value": null},{"op": "replace", "path": "/spec/customization/customLogoFile", "value": null}]'
  patchType: json
