apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mvo-migration-reader
  namespace: openshift-velero
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - velero-iam-credentials
  verbs:
  - get
