deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: NotIn
      values: ["4.5", "4.6", "4.7", "4.8", "4.9", "4.10", "4.11", "4.12", "4.13", "4.14", "4.15", "4.16"]
    - key: ext-managed.openshift.io/uwm-disabled
      operator: In
      values: ["true"]
    - key: ext-hypershift.openshift.io/cluster-type
      operator: NotIn
      values: ["management-cluster"]
